spc_example_data <- data.frame(
  shorthospitalname = 'Hospital',
  descriptionshort = 'Example Indicator',
  numerator = c(20,25,17,22,18,18,20,29,18,23,17,18,15,18,17,21,30,19,15,17,22,24,20,13,14,18,14,15,21,27,19,24,25,15,26,22),
  denominator = c(86,91,99,110,96,110,96,97,105,87,94,89,102,106,107,95,106,132,95,117,97,99,108,106,101,96,96,98,105,117,94,77,97,90,106,107),
  period_start = seq(from = as.Date('2019-01-01'), to = as.Date('2021-12-01'), by = 'month'),
  period_end = seq(from = as.Date('2019-02-01'), to = as.Date('2022-01-01'), by = 'month')-1,
  spccharttype = 'p',
  multiplier = 1,
  betteris = 'Lower',
  y_axis_label = 'Proportion'
)
spc_example_plotly <- function(spc_example_data) {
  controlcharts::spc(data = spc_example_data,
                     keys = period_end,
                     numerators = numerator,
                     denominators = denominator,
                     spc_settings = list(chart_type = "p"),
                     y_axis_settings = list(ylimit_label = "Proportion",
                                            ylimit_sig_figs = 0,
                                            ylimit_label_size = 14),
                     outlier_settings = list(improvement_direction = "decrease",
                                             astronomical = TRUE,
                                             shift = TRUE,
                                             trend = TRUE,
                                             two_in_three = TRUE),
                     canvas_settings = list(upper_padding = 40),
                     nhs_icon_settings = list(show_variation_icons = TRUE),
                     date_settings = list(date_format_day = "(blank)",
                                          date_format_month = "Mon",
                                          date_format_year = "YY"))
}
# Example data for different patterns
spc_example_data_astro <- spc_example_data
spc_example_data_astro[32,3] <- 30

spc_example_data_trend <- spc_example_data
spc_example_data_trend[30, 3] <- 26
spc_example_data_trend[31, 3] <- 26

spc_example_data_twothree <- spc_example_data
spc_example_data_twothree[33, 3] <- 29

spc_example_data_shift <- spc_example_data

spc_example_data_shift[29, 3] <- 26
spc_example_data_shift[31, 3] <- 21
spc_example_data_shift[34, 3] <- 21
spc_example_data_shift[36, 3] <- 25

fpl_example_data <- data.frame(
  establishment = rep(1:10, each = 12),
  shorthospitalname = c(rep(paste0('Hospital ', 1:9), each = 12), rep('Outlier', each = 12)),
  threeletteracronym = c(rep(paste0('Hospital ', 1:9), each = 12), rep('Outlier', each = 12)),
  hsp_name_short = 'HSP',
  descriptionshort = 'Example Indicator',
  numerator = c(do.call(c, lapply(c(1,1,1,2,3,5,7,9,10), function(x) rpois(12, x * 2))), rpois(12, 6 * 3.5)),
  denominator = c(do.call(c, lapply(c(1,1,1,2,3,5,7,9,10), function(x) rpois(12, x * 10))), rpois(12, 6 * 10)),
  period_start = seq(from = as.Date('2021-01-01'), to = as.Date('2021-12-01'), by = 'month'),
  period_end = seq(from = as.Date('2021-02-01'), to = as.Date('2022-01-01'), by = 'month')-1,
  funnelcharttype = 'PR',
  multiplier = 1,
  y_axis_label = 'Proportion',
  betteris = 'Lower',
  indicator = 'Indicator')

funnel_example_plotly <- function(fpl_example_data) {
  controlcharts::funnel(data = fpl_example_data,
                        keys = establishment,
                        numerators = numerator,
                        denominators = denominator,
                        y_axis_settings = list(ylimit_label = "Proportion",
                                               ylimit_sig_figs = 1,
                                               ylimit_label_size = 14),
                        x_axis_settings = list(xlimit_label = "Number of patients",
                                               xlimit_label_size = 14),
                        outlier_settings = list(improvement_direction = "decrease",
                                                three_sigma = TRUE))
}


#Set the datatypes of incoming NCR fields
#c = Character, d = Double, l = Logical, t = Time
#Other data types can be found at ??readr::cols
colTypes <- readr::cols(
hname = "c",
pcode = "c",
seifa = "c",
aria = "c",
hid = "c",
patientid = "c",
sex = "d",
inds = "d",
doa = readr::col_date(format = '%d/%m/%Y'),
toa = "t",
age = "d",
htm = "d",
wkg = "d",
dop = readr::col_date(format = '%d/%m/%Y'),
top = "t",
po = "c",
smk = "c",
db = "c",
dbm = "c",
pvd1 = "c",
pvd2 = "c",
pcabg = "c",
dpcabg = readr::col_date(format = '%d/%m/%Y'),
ppci = "c",
dppci = readr::col_date(format = '%d/%m/%Y'),
pcr = "d",
npcr = "c",
eftp = "c",
def = readr::col_date(format = '%d/%m/%Y'),
eft = "c",
ef = "d",
efes = "c",
egfri = "d",
shock = "c",
oca = "c",
pint = "c",
acs = "c",
dso = readr::col_date(format = '%d/%m/%Y'),
tso = "t",
ntso = "c",
acst = "c",
iht = "c",
phn = "c",
tbd = "t",
spr = "c",
dfmc = readr::col_date(format = '%d/%m/%Y'),
tfmc = "t",
decgd = readr::col_date(format = '%d/%m/%Y'),
tecgd = "t",
pci = "c",
pel = "c",
gos = "c",
fut = "c",
adr = "c",
adrt_1 = "c",
adrt_2 = "c",
adrt_3 = "c",
adrt_4 = "c",
adrt_5 = "c",
adrt_6 = "c",
adrt_7 = "c",
adrt_8 = "c",
adrt_9 = "c",
pintr = "c",
vsr = "c",
vsrt = "c",
lr1_lesion = "c",
lr1_isr = "c",
lr1_isrst = "c",
lr1_lst = "c",
lr1_sit = "c",
lr2_lesion = "c",
lr2_isr = "c",
lr2_isrst = "c",
lr2_lst = "c",
lr2_sit = "c",
lr3_lesion = "c",
lr3_isr = "c",
lr3_isrst = "c",
lr3_lst = "c",
lr3_sit = "c",
lr4_lesion = "c",
lr4_isr = "c",
lr4_isrst = "c",
lr4_lst = "c",
lr4_sit = "c",
lr5_lesion = "c",
lr5_isr = "c",
lr5_isrst = "c",
lr5_lst = "c",
lr5_sit = "c",
tak = "d",
dap = "d",
tft = "d",
ihmi = "c",
ihpci = "c",
ihpcip = "c",
ihtvr = "c",
ihtlr = "c",
ihcab = "c",
ihpcab = "c",
ihtvcab = "c",
ihstr = "d",
ihstrt = "c",
ihbl = "d",
ihblsite = "c",
ihst = "c",
dis = "c",
dod = readr::col_date(format = '%d/%m/%Y'),
crehab = "c",
mortc = "c",
dasp = "c",
doap = "c",
dstp = "c",
doll = "c",
dfu30 = readr::col_date(format = '%d/%m/%Y'),
stat30 = "c",
dmort30 = readr::col_date(format = '%d/%m/%Y'),
mort30r = "c",
mi30 = "c",
st30 = "c",
nstr = "c",
nstrt = "c",
crh30 = "c",
rhdte = readr::col_date(format = '%d/%m/%Y'),
pc30 = "c",
pci30 = "c",
tvr30 = "c",
tlr30 = "c",
cab30 = "c",
tvcab30 = "c",
crh30_2 = "c",
rhdte_2 = readr::col_date(format = '%d/%m/%Y'),
pc30_2 = "c",
pci30_2 = "c",
tvr30_2 = "c",
tlr30_2 = "c",
cab30_2 = "c",
tvcab30_2 = "c",
crh30_3 = "c",
rhdte_3 = readr::col_date(format = '%d/%m/%Y'),
pc30_3 = "c",
pci30_3 = "c",
tvr30_3 = "c",
tlr30_3 = "c",
cab30_3 = "c",
tvcab30_3 = "c",
crh30_4 = "c",
rhdte_4 = readr::col_date(format = '%d/%m/%Y'),
pc30_4 = "c",
pci30_4 = "c",
tvr30_4 = "c",
tlr30_4 = "c",
cab30_4 = "c",
tvcab30_4 = "c",
crh30_5 = "c",
rhdte_5 = readr::col_date(format = '%d/%m/%Y'),
pc30_5 = "c",
pci30_5 = "c",
tvr30_5 = "c",
tlr30_5 = "c",
cab30_5 = "c",
tvcab30_5 = "c",
crh30_6 = "c",
rhdte_6 = readr::col_date(format = '%d/%m/%Y'),
pc30_6 = "c",
pci30_6 = "c",
tvr30_6 = "c",
tlr30_6 = "c",
cab30_6 = "c",
tvcab30_6 = "c"
)
