#Set the datatypes of incoming NCR fields
#c = Character, d = Double, l = Logical, t = Time
#Other data types can be found at ??readr::cols
colTypes <- readr::cols(
hname = "c",
pcode = "c",
seifa = "c",
aria = "c",
hid = "c",
patientid = "c",
sex = "c",
inds = "c",
doa = readr::col_date(format = '%d/%m/%Y'),
toa = "t",
age = "d",
htm = "d",
wkg = "d",
dop = readr::col_date(format = '%d/%m/%Y'),
top = "t",
po = "c",
smk = "c",
db = "c",
dbm = "c",
pvd1 = "c",
pvd2 = "c",
pcabg = "c",
dpcabg = readr::col_date(format = '%d/%m/%Y'),
ppci = "c",
dppci = readr::col_date(format = '%d/%m/%Y'),
pcr = "d",
npcr = "c",
eftp = "c",
def = readr::col_date(format = '%d/%m/%Y'),
eft = "c",
ef = "d",
efes = "c",
egfri = "d",
shock = "c",
oca = "c",
pint = "c",
acs = "c",
dso = readr::col_date(format = '%d/%m/%Y'),
tso = "t",
ntso = "c",
acst = "c",
iht = "c",
phn = "c",
tbd = "t",
spr = "c",
dfmc = readr::col_date(format = '%d/%m/%Y'),
tfmc = "t",
decgd = readr::col_date(format = '%d/%m/%Y'),
tecgd = "t",
pci = "c",
pel = "c",
gos = "c",
fut = "c",
adr = "c",
adrt_1 = "c",
adrt_2 = "c",
adrt_3 = "c",
adrt_4 = "c",
adrt_5 = "c",
adrt_6 = "c",
adrt_7 = "c",
adrt_8 = "c",
adrt_9 = "c",
pintr = "c",
vsr = "c",
vsrt = "c",
lr1_lesion = "c",
lr1_isr = "c",
lr1_isrst = "c",
lr1_lst = "c",
lr1_sit = "c",
lr2_lesion = "c",
lr2_isr = "c",
lr2_isrst = "c",
lr2_lst = "c",
lr2_sit = "c",
lr3_lesion = "c",
lr3_isr = "c",
lr3_isrst = "c",
lr3_lst = "c",
lr3_sit = "c",
lr4_lesion = "c",
lr4_isr = "c",
lr4_isrst = "c",
lr4_lst = "c",
lr4_sit = "c",
lr5_lesion = "c",
lr5_isr = "c",
lr5_isrst = "c",
lr5_lst = "c",
lr5_sit = "c",
tak = "d",
dap = "d",
tft = "d",
ihmi = "c",
ihpci = "c",
ihpcip = "c",
ihtvr = "c",
ihtlr = "c",
ihcab = "c",
ihpcab = "c",
ihtvcab = "c",
ihstr = "d",
ihstrt = "c",
ihbl = "c",
ihblsite = "c",
ihst = "c",
dis = "c",
dod = readr::col_date(format = '%d/%m/%Y'),
crehab = "c",
mortc = "c",
dasp = "c",
doap = "c",
dstp = "c",
doll = "c",
dfu30 = readr::col_date(format = '%d/%m/%Y'),
stat30 = "c",
dmort30 = readr::col_date(format = '%d/%m/%Y'),
mort30r = "c",
mi30 = "c",
st30 = "c",
nstr = "c",
nstrt = "c",
crh30 = "c",
rhdte = readr::col_date(format = '%d/%m/%Y'),
pc30 = "c",
pci30 = "c",
tvr30 = "c",
tlr30 = "c",
cab30 = "c",
tvcab30 = "c",
crh30_2 = "c",
rhdte_2 = readr::col_date(format = '%d/%m/%Y'),
pc30_2 = "c",
pci30_2 = "c",
tvr30_2 = "c",
tlr30_2 = "c",
cab30_2 = "c",
tvcab30_2 = "c",
crh30_3 = "c",
rhdte_3 = readr::col_date(format = '%d/%m/%Y'),
pc30_3 = "c",
pci30_3 = "c",
tvr30_3 = "c",
tlr30_3 = "c",
cab30_3 = "c",
tvcab30_3 = "c",
crh30_4 = "c",
rhdte_4 = readr::col_date(format = '%d/%m/%Y'),
pc30_4 = "c",
pci30_4 = "c",
tvr30_4 = "c",
tlr30_4 = "c",
cab30_4 = "c",
tvcab30_4 = "c",
crh30_5 = "c",
rhdte_5 = readr::col_date(format = '%d/%m/%Y'),
pc30_5 = "c",
pci30_5 = "c",
tvr30_5 = "c",
tlr30_5 = "c",
cab30_5 = "c",
tvcab30_5 = "c",
crh30_6 = "c",
rhdte_6 = readr::col_date(format = '%d/%m/%Y'),
pc30_6 = "c",
pci30_6 = "c",
tvr30_6 = "c",
tlr30_6 = "c",
cab30_6 = "c",
tvcab30_6 = "c"
)
