---
title: "PCI Reports"
format:
  docx:
    toc: true
    number-sections: true
    highlight-style: github
editor: visual
execute: 
  echo: false
---

```{r Data download, include=FALSE}
#Setup Temporary Directory for file storage
temp <- tempdir()
#Load in the helper functions/data required
source("HelperFunctions.R")
#Set data source type Powerbi or Sharepoint
data_source <- "Powerbi"

if(data_source == "Sharepoint"){
  #Sharepoint Token
tk_sp <- qiverse.azure::get_az_tk('sp')
#Load data from CSV
fsh_data <- qiverse.sharepoint::download_sharepoint_file(
  site_url = 'https://wahealthdept.sharepoint.com/sites/WACardiacOutcomeRegistry',
  file_url = 'https://wahealthdept.sharepoint.com/:x:/r/sites/WACardiacOutcomeRegistry/PCI/PCI%20Data/Latest%20NCR%20Submission/Fiona_Stanley_Hospital_2024_PCI_Data.csv?d=w502a1115d07d84e37976119fd0e5ed4e4&csf=1&web=1&e=CipGly',
  token = tk_sp)
rph_data <- qiverse.sharepoint::download_sharepoint_file(
  site_url = 'https://wahealthdept.sharepoint.com/sites/WACardiacOutcomeRegistry',
  file_url = 'https://wahealthdept.sharepoint.com/:x:/r/sites/WACardiacOutcomeRegistry/PCI/PCI%20Data/Latest%20NCR%20Submission/Royal_Perth_Hospital_2024_PCI_Data.csv?d=w7b047d9021874a58bd3241d2ad4837ef&csf=1&web=1&e=HXmpC4',
  token = tk_sp)
scgh_data <- qiverse.sharepoint::download_sharepoint_file(
  site_url = 'https://wahealthdept.sharepoint.com/sites/WACardiacOutcomeRegistry',
  file_url = 'https://wahealthdept.sharepoint.com/:x:/r/sites/WACardiacOutcomeRegistry/PCI/PCI%20Data/Latest%20NCR%20Submission/Sir_Charles_Gairdner_Hospital_2024_PCI_Data.csv?d=w970e2c01ddec4e8aa6456876e8c793b5&csf=1&web=1&e=Jc7bIW',
  token = tk_sp)

#Read in data from CSV
pci_data <- readr::read_csv(c(fsh_data, rph_data, scgh_data), col_types = colTypes)
} else if(data_source == "Powerbi"){
#PowerBI Token
tk = qiverse.azure::get_az_tk('pbi_df')
#Load data from PowerBI
data <- qiverse.powerbi::download_dataflow_table(workspace_name = "PCI Data Set",
                                              dataflow_name = "NCR Template and Hid files",
                                              table_name = "required_columns",
                                              access_token = tk$credentials$access_token)
#Workaround for setting csv col types
readr::write_csv(data, paste0(temp, ".csv"))
#Read in data from PowerBI
pci_data <- readr::read_csv(paste0(temp, ".csv"), col_types = colTypes)
}

```

```{r Data transformation, include=FALSE}


#Creating period start and end, first and last date of the month
pci_data <- pci_data |> 
  dplyr::mutate(period_start = lubridate::floor_date(dop, unit = "month"),
                period_end = lubridate::ceiling_date(period_start, unit = "month")-1)

#NCR 8
pci_data <- pci_data |> 
  dplyr::mutate(NCR8_den = 1,
                NCR8_num = dplyr::if_else((dop + 30) <= dmort30 | dis == "6", 1, 0, missing = 0))


#Group data for the funnel plot function
ncr8_fpl_data <- pci_data |> 
  dplyr::group_by(hname) |>
  dplyr::summarise(
    NCR8_Num = sum(NCR8_num),
    NCR8_Den = sum(NCR8_den))

#Group data for the SPC function
ncr8_spc_data <- pci_data |> 
  dplyr::group_by(period_start, period_end) |>
  dplyr::summarise(
    NCR8_Num = sum(NCR8_num),
    NCR8_Den = sum(NCR8_den))
  

#NCR 9
pci_data <- pci_data |> 
  dplyr::mutate(NCR9_den = dplyr::if_else(dis != "6" & 
                                          dstp != "2" & 
                                          doll != "2" & 
                                          is.na(dstp) == F &
                                          is.na(doll) == F &
                                          dstp != "3" & 
                                          doll != "3" & 
                                          dstp != "" & 
                                          doll != "", 1, 0, missing = 0),
                NCR9_num = dplyr::if_else(NCR9_den == 1 & 
                                         (dstp == "1" | doll == "1"), 1, 0, missing = 0))

#Group data for the funnel plot function
ncr9_fpl_data <- pci_data |> 
  dplyr::group_by(hname) |>
  dplyr::summarise(
    NCR9_Num = sum(NCR9_num),
    NCR9_Den = sum(NCR9_den))

#Group data for the SPC function
ncr9_spc_data <- pci_data |> 
  dplyr::group_by(period_start, period_end) |>
  dplyr::summarise(
    NCR9_Num = sum(NCR9_num),
    NCR9_Den = sum(NCR9_den))


#NCR 10
pci_data <- pci_data |> 
  dplyr::mutate(NCR10_den = dplyr::if_else(dis != "6" &
                                           crehab != "-1" &
                                           crehab != "", 1, 0, missing = 0),
                NCR10_num = dplyr::if_else(NCR10_den == 1 & 
                                           crehab == "1", 1, 0, missing = 0))

#Group data for the funnel plot function
ncr10_fpl_data <- pci_data |> 
  dplyr::group_by(hname) |>
  dplyr::summarise(
    NCR10_Num = sum(NCR10_num),
    NCR10_Den = sum(NCR10_den))

#Group data for the SPC function
ncr10_spc_data <- pci_data |> 
  dplyr::group_by(period_start, period_end) |>
  dplyr::summarise(
    NCR10_Num = sum(NCR10_num),
    NCR10_Den = sum(NCR10_den))


#NCR 11
pci_data <- pci_data |> 
  dplyr::mutate(NCR11_den = dplyr::if_else(dis != "6" & 
                                           dasp != "2" & 
                                           doap != "2" & 
                                           is.na(dasp) == F &
                                           is.na(doap) == F &
                                           dasp != "3" & 
                                           doap != "3" & 
                                           dasp != "" & 
                                           doap != "", 1, 0, missing = 0),
                NCR11_num = dplyr::if_else(NCR11_den == 1 & 
                                          (dasp == "1" | doap == "1"), 1, 0, missing = 0))

#Group data for the funnel plot function
ncr11_fpl_data <- pci_data |> 
  dplyr::group_by(hname) |>
  dplyr::summarise(
    NCR11_Num = sum(NCR11_num),
    NCR11_Den = sum(NCR11_den))

#Group data for the SPC function
ncr11_spc_data <- pci_data |> 
  dplyr::group_by(period_start, period_end) |>
  dplyr::summarise(
    NCR11_Num = sum(NCR11_num),
    NCR11_Den = sum(NCR11_den))
```

## NCR 8: 30 Day Mortality

### Funnel

```{r NCR8 Funnel}
tempFile <- paste0(temp, "/NCR8_fpl.html")
qiverse.qiplotly::fpl_plotly_create(numerator = ncr8_fpl_data$NCR8_Num,
                  denominator = ncr8_fpl_data$NCR8_Den,
                  group = ncr8_fpl_data$hname,
                  y_limit_upper = 10,
                  title = "30 Day Mortality",
                  better_is = "Lower",
                  funnel_period_start = min(pci_data$period_start),
                  funnel_period_end = max(pci_data$period_end)) |> 
  #Save the plotly plot into a html file - required to output to word
  htmlwidgets::saveWidget(file = tempFile)
#Snapshot the html file and save it as a png
webshot::webshot(url = tempFile, file = "Plots/NCR8_fpl.png")
```

### SPC

```{r NCR8 SPC}
tempFile <- paste0(temp, "/NCR8_spc.html")
qiverse.qiplotly::spc_plotly_create(x = as.Date(ncr8_spc_data$period_end),
                                    numerator = ncr8_spc_data$NCR8_Num,
                                    denominator = ncr8_spc_data$NCR8_Den,
                                    title = "30 Day Mortality",
                                    better_is = "Lower",
                                    spc_period_start = min(pci_data$period_start),
                                    spc_period_end = max(pci_data$period_end)) |> 
  htmlwidgets::saveWidget(file = tempFile) 

webshot::webshot(url = tempFile, file = "Plots/NCR8_spc.png")
```

## NCR 9: Patients Discharged on Lipid-Lowering Therapy

### Funnel

```{r NCR9 Funnel}
tempFile <- paste0(temp, "/NCR9_fpl.html")
qiverse.qiplotly::fpl_plotly_create(numerator = ncr9_fpl_data$NCR9_Num,
                  denominator = ncr9_fpl_data$NCR9_Den,
                  group = ncr9_fpl_data$hname,
                  title = "Discharged on Lipid-Lowering Therapy",
                  better_is = "Higher",
                  funnel_period_start = min(pci_data$period_start),
                  funnel_period_end = max(pci_data$period_end)) |> 
  htmlwidgets::saveWidget(file = tempFile)

webshot::webshot(url = tempFile, file = "Plots/NCR9_fpl.png")
```

### SPC

```{r NCR9 SPC}
tempFile <- paste0(temp, "/NCR9_spc.html")
qiverse.qiplotly::spc_plotly_create(x = as.Date(ncr9_spc_data$period_end),
                                    numerator = ncr9_spc_data$NCR9_Num,
                                    denominator = ncr9_spc_data$NCR9_Den,
                                    title = "Discharged on Lipid-Lowering Therapy",
                                    better_is = "Higher",
                                    spc_period_start = min(pci_data$period_start),
                                    spc_period_end = max(pci_data$period_end)) |> 
  htmlwidgets::saveWidget(file = tempFile)

webshot::webshot(url = tempFile, file = "Plots/NCR9_spc.png")
```

## NCR 10: Patients Referred to Cardiac Rehabilitation

### Funnel

```{r NCR10 Funnel}
tempFile <- paste0(temp, "/NCR10_fpl.html")
qiverse.qiplotly::fpl_plotly_create(numerator = ncr10_fpl_data$NCR10_Num,
                  denominator = ncr10_fpl_data$NCR10_Den,
                  group = ncr10_fpl_data$hname,
                  title = "Referred to Cardiac Rehabilitation",
                  better_is = "Higher",
                  funnel_period_start = min(pci_data$period_start),
                  funnel_period_end = max(pci_data$period_end)) |> 
  htmlwidgets::saveWidget(file = tempFile)

webshot::webshot(url = tempFile, file = "Plots/NCR10_fpl.png")
```

### SPC

```{r NCR10 SPC}
tempFile <- paste0(temp, "/NCR10_spc.html")
qiverse.qiplotly::spc_plotly_create(x = as.Date(ncr10_spc_data$period_end),
                                    numerator = ncr10_spc_data$NCR10_Num,
                                    denominator = ncr10_spc_data$NCR10_Den,
                                    title = "Referred to Cardiac Rehabilitation",
                                    better_is = "Higher",
                                    spc_period_start = min(pci_data$period_start),
                                    spc_period_end = max(pci_data$period_end)) |> 
  htmlwidgets::saveWidget(file = tempFile)

webshot::webshot(url = tempFile, file = "Plots/NCR10_spc.png")
```

## NCR 11: Patients Discharged on Dual Antiplatelet Therapy

### Funnel

```{r NCR11 Funnel}
tempFile <- paste0(temp, "/NCR11_fpl.html")
qiverse.qiplotly::fpl_plotly_create(numerator = ncr11_fpl_data$NCR11_Num,
                  denominator = ncr11_fpl_data$NCR11_Den,
                  group = ncr11_fpl_data$hname,
                  title = "Discharged on Dual Antiplatelet Therapy",
                  better_is = "Higher",
                  funnel_period_start = min(pci_data$period_start),
                  funnel_period_end = max(pci_data$period_end)) |> 
  htmlwidgets::saveWidget(file = tempFile)

webshot::webshot(url = tempFile, file = "Plots/NCR11_fpl.png")
```

### SPC

```{r NCR11 SPC}
tempFile <- paste0(temp, "/NCR11_spc.html")
qiverse.qiplotly::spc_plotly_create(x = as.Date(ncr11_spc_data$period_end),
                                    numerator = ncr11_spc_data$NCR11_Num,
                                    denominator = ncr11_spc_data$NCR11_Den,
                                    title = "Discharged on Dual Antiplatelet Therapy",
                                    better_is = "Higher",
                                    spc_period_start = min(pci_data$period_start),
                                    spc_period_end = max(pci_data$period_end)) |> 
  htmlwidgets::saveWidget(file = tempFile)

webshot::webshot(url = tempFile, file = "Plots/NCR11_spc.png")
```
