---
title: "<span style='color:#0047AB; font-family:Arial;'>Customised Percutaneous Coronary Interventions Report</span>"
format:
  docx:
    toc: true
    number-sections: true
    highlight-style: github
    fig-format: svg
execute:
  echo: false
---

```{r data import, include=FALSE}
library(qiverse.azure)
if (!file.exists("./pci_data.csv")) {
  stop("NCR dataset not found! Please check that you have a single CSV file named 'pci_data.csv' in the current directory!",
       call. = FALSE)
}
#Load in the helper functions/data required
source("HelperFunctions.R")

# PowerBI Token
tk <- qiverse.azure::get_az_tk('pbi_df')
# Load data from PowerBI
pci_data <- qiverse.powerbi::download_dataflow_table(workspace_name = "PCI Data Set",
                                                dataflow_name = "Redcap PCI Registry",
                                                table_name = "PCIRegistryData",
                                                access_token = tk$credentials$access_token, verbose = TRUE)
```

```{r Data transformation, include=FALSE}
#Create period start and end, first and last date of the month
pci_data <- pci_data |>
  dplyr::mutate(dop = as.Date(dop_top),
  period_start = lubridate::floor_date(dop, unit = "month"),
  period_end = lubridate::ceiling_date(period_start, unit = "month")-1,
#Create numerator columns
  prev_cabg_num = dplyr::if_else(pcabg == "Yes", 1, 0),
  prev_pci_num = dplyr::if_else(ppci == "Yes", 1, 0),
  prev_oca_num = dplyr::if_else(arrest_pre_pci == "Yes", 1, 0),
  dis_length = dplyr::case_when(
    dod == dop ~ "SDD",
    (dod-dop) >= 2 ~ ">1 day",
    (dod-dop) >= 1 ~ "1 day",
    .default = "Unknown")) |>
#Missing data filters
  dplyr::filter(!is.na(period_end)) |>
  dplyr::filter(period_end <= Sys.Date())

```

\newpage

## Proportion of Patients with a previous PCI

### SPC Chart
```{r spc_setup_ppci, echo=FALSE} 
#| fig.cap="SPC chart for the proportion of patients with a previous PCI"
spc_data <- controlcharts::spc(
  data = pci_data,
  keys = period_end,
  numerators = prev_pci_num,
  denominators = rep(1, nrow(pci_data)),
  spc_settings = list(chart_type = "p"),
  y_axis_settings = list(ylimit_label = "% Patients with a previous PCI", ylimit_label_size = 14, ylimit_tick_rotation = 0, ylimit_sig_figs = 0),
  outlier_settings = list(improvement_direction = "decrease", astronomical = TRUE, shift = TRUE, trend = TRUE, two_in_three = TRUE),
  nhs_icon_settings = list(show_variation_icons = TRUE),
  date_settings = list(date_format_day = "(blank)", date_format_month = "Mon", date_format_year = "YY")
)
spc_data
```

``` {r spc_patterns_ppci, echo=FALSE}
#Filter the spc limits data to get the latest patterns identified
astpoint <- spc_data$limits |> dplyr::filter(astpoint != "none")
#Filter to the last point in the ordered dates
astpoint <- astpoint$date[length(astpoint$date)]
trend <- spc_data$limits |> dplyr::filter(trend != "none")
trend <- trend$date[length(trend$date)]
shift <- spc_data$limits |> dplyr::filter(shift != "none")
shift <- shift$date[length(shift$date)]
two_in_three <- spc_data$limits |> dplyr::filter(two_in_three != "none")
two_in_three <- two_in_three$date[length(two_in_three$date)]

pattern_text <- "Using the Making Data Count approach, the following most recent patterns have been identified in the SPC chart: "
#Only include text if a pattern was identified
if(length(astpoint) == 1) {
  pattern_text <- stringr::str_flatten(c(pattern_text, paste0("An astronomical point was identified on ", astpoint, ". ")))}
if(length(trend) == 1) {
  pattern_text <- stringr::str_flatten(c(pattern_text, paste0("A trend was identified on ", trend, ". ")))}
if(length(shift) == 1) {
  pattern_text <- stringr::str_flatten(c(pattern_text, paste0("A shift was identified on ", shift, ". ")))}
if(length(two_in_three) == 1) {
   pattern_text <- stringr::str_flatten(c(pattern_text, paste0("A two in three was identified on ", two_in_three, ". ")))}

if(stringr::str_length(pattern_text) != 112) patttern_text <- "Using the Making Data Count approach, no patterns were identified in the SPC chart."

```

`r pattern_text`

### Funnel Plot
```{r fpl_setup_ppci, echo=FALSE}
#| fig.cap="Funnel plot for the proportion of patients with a previous PCI"
fpl_data <- controlcharts::funnel(
  data = pci_data,
  keys = centre,
  numerators = prev_pci_num,
  denominators = rep(1, nrow(pci_data)),
  y_axis_settings = list(ylimit_label = paste0("% Patients with a previous PCI"), ylimit_label_size = 14, ylimit_sig_figs = 1),
  outlier_settings = list(improvement_direction = "decrease", three_sigma = TRUE)
)
fpl_data
```

``` {r fpl_patterns_ppci, echo=FALSE}
#Filter the spc limits data to get the latest patterns identified
astpoint <- fpl_data$limits |> dplyr::filter(three_sigma == "deterioration")

pattern_text <- "Using the Making Data Count approach, no patterns were identified in the Funnel Plot."
#Only include text if a pattern was identified
pattern_text <- if(length(astpoint$group) != 0) {
    pattern_text <- paste0("An astronomical point was identified for ", stringr::str_flatten(astpoint$group, collapse = ", "), ".")}

```

`r pattern_text`

\newpage

## Proportion of Patients with a previous CABG

### SPC Chart
```{r spc_setup_pcabg, echo=FALSE} 
#| fig.cap="SPC chart for the proportion of patients with a previous CABG"
spc_data <- controlcharts::spc(
  data = pci_data,
  keys = period_end,
  numerators = prev_cabg_num,
  denominators = rep(1, nrow(pci_data)),
  spc_settings = list(chart_type = "p"),
  y_axis_settings = list(ylimit_label = "% Patients with a previous CABG", ylimit_label_size = 14, ylimit_tick_rotation = 0, ylimit_sig_figs = 0),
  outlier_settings = list(improvement_direction = "decrease", astronomical = TRUE, shift = TRUE, trend = TRUE, two_in_three = TRUE),
  nhs_icon_settings = list(show_variation_icons = TRUE),
  date_settings = list(date_format_day = "(blank)", date_format_month = "Mon", date_format_year = "YY")
)
spc_data
```

``` {r spc_patterns_pcabg, echo=FALSE}
#Filter the spc limits data to get the latest patterns identified
astpoint <- spc_data$limits |> dplyr::filter(astpoint != "none")
#Filter to the last point in the ordered dates
astpoint <- astpoint$date[length(astpoint$date)]
trend <- spc_data$limits |> dplyr::filter(trend != "none")
trend <- trend$date[length(trend$date)]
shift <- spc_data$limits |> dplyr::filter(shift != "none")
shift <- shift$date[length(shift$date)]
two_in_three <- spc_data$limits |> dplyr::filter(two_in_three != "none")
two_in_three <- two_in_three$date[length(two_in_three$date)]

pattern_text <- "Using the Making Data Count approach, the following most recent patterns have been identified in the SPC chart: "
#Only include text if a pattern was identified
if(length(astpoint) == 1) {
  pattern_text <- stringr::str_flatten(c(pattern_text, paste0("An astronomical point was identified on ", astpoint, ". ")))}
if(length(trend) == 1) {
  pattern_text <- stringr::str_flatten(c(pattern_text, paste0("A trend was identified on ", trend, ". ")))}
if(length(shift) == 1) {
  pattern_text <- stringr::str_flatten(c(pattern_text, paste0("A shift was identified on ", shift, ". ")))}
if(length(two_in_three) == 1) {
   pattern_text <- stringr::str_flatten(c(pattern_text, paste0("A two in three was identified on ", two_in_three, ". ")))}

if(stringr::str_length(pattern_text) != 112) patttern_text <- "Using the Making Data Count approach, no patterns were identified in the SPC chart."
```

`r pattern_text`

### Funnel Plot
```{r fpl_setup_pcabg, echo=FALSE}
#| fig.cap="Funnel plot for the proportion of patients with a previous CABG"
fpl_data <- controlcharts::funnel(
  data = pci_data,
  keys = centre,
  numerators = prev_cabg_num,
  denominators = rep(1, nrow(pci_data)),
  y_axis_settings = list(ylimit_label = paste0("% Patients with a previous CABG"), ylimit_label_size = 14, ylimit_sig_figs = 1),
  outlier_settings = list(improvement_direction = "decrease", three_sigma = TRUE)
)
fpl_data
```

``` {r fpl_patterns_pcabg, echo=FALSE}
#Filter the spc limits data to get the latest patterns identified
astpoint <- fpl_data$limits |> dplyr::filter(three_sigma == "deterioration")

pattern_text <- "Using the Making Data Count approach, no patterns were identified in the Funnel Plot."
#Only include text if a pattern was identified
pattern_text <- if(length(astpoint$group) != 0) {
    pattern_text <- paste0("An astronomical point was identified for ", stringr::str_flatten(astpoint$group, collapse = ", "), ".")}

```

`r pattern_text`

\newpage

## Proportion of Patients with a previous OHCA

### SPC Chart
```{r spc_setup_pOHCA, echo=FALSE} 
#| fig.cap="SPC chart for the proportion of patients with a previous OHCA"
spc_data <- controlcharts::spc(
  data = pci_data,
  keys = period_end,
  numerators = prev_oca_num,
  denominators = rep(1, nrow(pci_data)),
  spc_settings = list(chart_type = "p"),
  y_axis_settings = list(ylimit_label = "% Patients with a previous OHCA", ylimit_label_size = 14, ylimit_tick_rotation = 0, ylimit_sig_figs = 0),
  outlier_settings = list(improvement_direction = "decrease", astronomical = TRUE, shift = TRUE, trend = TRUE, two_in_three = TRUE),
  nhs_icon_settings = list(show_variation_icons = TRUE),
  date_settings = list(date_format_day = "(blank)", date_format_month = "Mon", date_format_year = "YY")
)
spc_data
```

``` {r spc_patterns_pOHCA, echo=FALSE}
#Filter the spc limits data to get the latest patterns identified
astpoint <- spc_data$limits |> dplyr::filter(astpoint != "none")
#Filter to the last point in the ordered dates
astpoint <- astpoint$date[length(astpoint$date)]
trend <- spc_data$limits |> dplyr::filter(trend != "none")
trend <- trend$date[length(trend$date)]
shift <- spc_data$limits |> dplyr::filter(shift != "none")
shift <- shift$date[length(shift$date)]
two_in_three <- spc_data$limits |> dplyr::filter(two_in_three != "none")
two_in_three <- two_in_three$date[length(two_in_three$date)]

pattern_text <- "Using the Making Data Count approach, the following most recent patterns have been identified in the SPC chart: "
#Only include text if a pattern was identified
if(length(astpoint) == 1) {
  pattern_text <- stringr::str_flatten(c(pattern_text, paste0("An astronomical point was identified on ", astpoint, ". ")))}
if(length(trend) == 1) {
  pattern_text <- stringr::str_flatten(c(pattern_text, paste0("A trend was identified on ", trend, ". ")))}
if(length(shift) == 1) {
  pattern_text <- stringr::str_flatten(c(pattern_text, paste0("A shift was identified on ", shift, ". ")))}
if(length(two_in_three) == 1) {
   pattern_text <- stringr::str_flatten(c(pattern_text, paste0("A two in three was identified on ", two_in_three, ". ")))}

if(stringr::str_length(pattern_text) != 112) patttern_text <- "Using the Making Data Count approach, no patterns were identified in the SPC chart."


```

`r pattern_text`

### Funnel Plot
```{r fpl_setup_pOHCA, echo=FALSE}
#| fig.cap="Funnel plot for the proportion of patients with a previous OHCA"
fpl_data <- controlcharts::funnel(
  data = pci_data,
  keys = centre,
  numerators = prev_oca_num,
  denominators = rep(1, nrow(pci_data)),
  y_axis_settings = list(ylimit_label = paste0("% Patients with a previous OHCA"), ylimit_label_size = 14, ylimit_sig_figs = 1),
  outlier_settings = list(improvement_direction = "decrease", three_sigma = TRUE)
)
fpl_data
```

``` {r fpl_patterns_pOHCA, echo=FALSE}
#Filter the spc limits data to get the latest patterns identified
astpoint <- fpl_data$limits |> dplyr::filter(three_sigma == "deterioration")

pattern_text <- "Using the Making Data Count approach, no patterns were identified in the Funnel Plot."
#Only include text if a pattern was identified
pattern_text <- if(length(astpoint$group) != 0) {
    pattern_text <- paste0("An astronomical point was identified for ", stringr::str_flatten(astpoint$group, collapse = ", "), ".")}

```

`r pattern_text`

\newpage

```{r demographics_sex, echo=FALSE}
# Plotting the distribution of patients by sex
ggplot2::ggplot(pci_data, ggplot2::aes(x = sex)) +
  ggplot2::geom_bar(fill = "steelblue") +
  ggplot2::labs(title = "Distribution of Patients by Sex",
       x = "Sex",
       y = "Count") +
  ggplot2::theme_minimal() +
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5, size = 10, face = "bold"))

```

```{r demographics_inds, echo=FALSE}
# Plotting the distribution of patients by Indigenous status
ggplot2::ggplot(pci_data, ggplot2::aes(x = inds)) +
  ggplot2::geom_bar(fill = "steelblue") +
  ggplot2::labs(title = "Distribution of Patients by Aboriginal or Torres Strait Islander Identity",
       x = "Aboriginal or Torres Strait Islander Identity",
       y = "Count") +
  ggplot2::theme_minimal() +
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5, size = 10, face = "bold"))

```

```{r demographics_age, echo=FALSE}
# Plotting the distribution of patients by age
ggplot2::ggplot(pci_data, ggplot2::aes(x = age)) +
  ggplot2::geom_bar(fill = "steelblue") +
  ggplot2::labs(title = "Distribution of Patients by Age",
       x = "Age",
       y = "Count") +
  ggplot2::theme_minimal() +
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5, size = 10, face = "bold"))

```

```{r procedures, echo=FALSE}
# Plotting the distribution of patients by ACS Type
ggplot2::ggplot(pci_data, ggplot2::aes(x = type_acs)) +
  ggplot2::geom_bar(fill = "steelblue") +
  ggplot2::labs(title = "Distribution of Patients by ACS Type",
       x = "ACS Type",
       y = "Count") +
  ggplot2::theme_minimal() +
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5, size = 10, face = "bold"))

```

```{r same_day_discharge, echo=FALSE}
# Plotting the distribution of patients by ACS Type
ggplot2::ggplot(pci_data, ggplot2::aes(x = dis_length)) +
  ggplot2::geom_bar(fill = "steelblue") +
  ggplot2::labs(title = "Distribution of Patients by Same Day Discharge",
       x = "Same Day Discharge",
       y = "Count") +
  ggplot2::theme_minimal() +
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5, size = 10, face = "bold"))

```