<br>
## Proportion of Patients with a `r unique_indicator`

```{r, include=FALSE}
#| label: paste0("setup-", unique_indicator)
indicator_data <- data.frame(name = c("previous CABG", "previous PCI", "previous OHCA"), 
                             num = c("prev_cabg_num", "prev_pci_num", "prev_oca_num"),
                             improve = c("decrease", "decrease", "decrease"))

#Get the numerator column for the selected indicator
num <- indicator_data$num[indicator_data$name == unique_indicator]
#Extract the numerator values from the pci data
num <- pci_data[[num]]
#Get the direction of the SPC/Funnel highlighting column for the selected indicator
improve <- indicator_data$improve[indicator_data$name == unique_indicator]
```

```{r, fig.cap=paste0("SPC chart for the proportion of patients with a ", unique_indicator), fig.align="center", fig.style="italic"}
#| label: paste0("spc-", unique_indicator)
spc_data <- controlcharts::spc(
  data = pci_data,
  keys = period_end,
  numerators = num,
  denominators = rep(1, nrow(pci_data)),
  spc_settings = list(chart_type = "p"),
  y_axis_settings = list(ylimit_label = paste0("% Patients with ", unique_indicator), ylimit_label_size = 14),
  outlier_settings = list(improvement_direction = improve, astronomical = TRUE, shift = TRUE, trend = TRUE, two_in_three = TRUE),
  canvas_settings = list(upper_padding = 40),
  nhs_icon_settings = list(show_variation_icons = TRUE),
  date_settings = list(date_format_day = "(blank)", date_format_month = "Mon", date_format_year = "YY")
)
spc_data
```

``` {r, echo=FALSE}
#| label: paste0("spc-text-", unique_indicator)

#Filter the spc limits data to get the latest patterns identified
astpoint <- spc_data$limits |> dplyr::filter(astpoint != "none") |> dplyr::slice_max(order_by = date, n = 1)
trend <- spc_data$limits |> dplyr::filter(trend != "none") |> dplyr::slice_max(order_by = date, n = 1)
shift <- spc_data$limits |> dplyr::filter(shift != "none") |> dplyr::slice_max(order_by = date, n = 1)
two_in_three <- spc_data$limits |> dplyr::filter(two_in_three != "none") |> dplyr::slice_max(order_by = date, n = 1)

pattern_text <- ""
#Only include text if a pattern was identified
if(nrow(astpoint) == 1) pattern_text <- stringr::str_flatten(c(pattern_text, paste0("An astronomical point was identified on ", astpoint$date, ". ")))
if(nrow(trend) == 1) pattern_text <- stringr::str_flatten(c(pattern_text, paste0("A trend was identified on ", trend, ". ")))
if(nrow(shift) == 1) pattern_text <- stringr::str_flatten(c(pattern_text, paste0("A shift was identified on ", shift, ". ")))
if(nrow(two_in_three) == 1) pattern_text <- stringr::str_flatten(c(pattern_text, paste0("A two in three was identified on ", two_in_three, ". ")))

```

Using the Making Data Count approach, the following most recent patterns have been identified in the SPC chart: 
`r pattern_text`

```{r, echo=FALSE, fig.cap=paste0("Funnel plot for the proportion of patients with a ", unique_indicator), fig.align="center", fig.style="italic"}
#| label: paste0("fpl-", unique_indicator)
fpl_data <- controlcharts::funnel(
  data = pci_data,
  keys = hname,
  numerators = num,
  denominators = rep(1, nrow(pci_data)),
  y_axis_settings = list(ylimit_label = paste0("% Patients with ", unique_indicator), ylimit_label_size = 14),
  outlier_settings = list(improvement_direction = improve, three_sigma = TRUE)
)
fpl_data
```

``` {r, echo=FALSE}
#| label: paste0("fpl-text-", unique_indicator)
#Filter the spc limits data to get the latest patterns identified
astpoint <- fpl_data$limits |> dplyr::filter(three_sigma == "deterioration")

pattern_text <- ""
#Only include text if a pattern was identified
pattern_text <- paste0("An astronomical point was identified for ", stringr::str_flatten(astpoint$group, collapse = ", "))
```

Using the Making Data Count approach, the folowing patterns have been identified in the Funnel Plot: 
`r pattern_text`